config/routes.rb
Ratebeer::Application.routes.draw do
  resources :memberships, only: [:new, :create, :destroy] do
    post 'confirm', on: :member
  end

  resources :beer_clubs

  resources :users

  resources :beers
  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  root 'breweries#index'
  get 'brewerylist', to:'breweries#nglist'

  resources :styles

  resources :sessions, only: [:new, :create, :destroy]

  resources :ratings, only: [:index, :new, :create, :destroy]

  resources :places, only: [:index, :show]
  post 'places', to: 'places#search'

  get 'kaikki_bisset', to: 'beers#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#omniauth'
  get 'auth:/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy'

end

app/models/beer_club.rb
class BeerClub < ActiveRecord::Base

  has_many :memberships
  has_many :users, through: :memberships

  validates_presence_of :name, :founded, :city

  def member?(user)
    users.include? user and memberships.find_by(user_id:user.id).confirmed
  end
end

app/controllers/beer_clubs_controller.rb
class BeerClubsController < ApplicationController
  before_action :set_beer_club, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]
  before_action :ensure_that_admin, only: [:destroy]

  # GET /beer_clubs
  # GET /beer_clubs.json
  def index
    @beer_clubs = BeerClub.all
  end

  # GET /beer_clubs/1
  # GET /beer_clubs/1.json
  def show
    @membership = Membership.new
    @membership.beer_club = @beer_club
  end

  # GET /beer_clubs/new
  def new
    @beer_club = BeerClub.new
  end

  # GET /beer_clubs/1/edit
  def edit
  end

  # POST /beer_clubs
  # POST /beer_clubs.json
  def create
    @beer_club = BeerClub.new(beer_club_params)

    respond_to do |format|
      if @beer_club.save
        @beer_club.memberships.create user_id:current_user.id, confirmed:true
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully created.' }
        format.json { render action: 'show', status: :created, location: @beer_club }
      else
        format.html { render action: 'new' }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beer_clubs/1
  # PATCH/PUT /beer_clubs/1.json
  def update
    respond_to do |format|
      if @beer_club.update(beer_club_params)
        format.html { redirect_to @beer_club, notice: 'Beer club was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @beer_club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_clubs/1
  # DELETE /beer_clubs/1.json
  def destroy
    @beer_club.destroy
    respond_to do |format|
      format.html { redirect_to beer_clubs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer_club
      @beer_club = BeerClub.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_club_params
      params.require(:beer_club).permit(:name, :founded, :city)
    end
end

app/helpers/beer_clubs_helper.rb
module BeerClubsHelper
end

app/views/beer_clubs/_form.html.erb
<%= form_for(@beer_club) do |f| %>
  <% if @beer_club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_club.errors.count, "error") %> prohibited this beer_club from being saved:</h2>

      <ul>
      <% @beer_club.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :founded %><br>
    <%= f.text_field :founded %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beer_clubs/_list.html.erb
<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Founded</th>
    <th>City</th>
  </tr>
  </thead>

  <tbody>
  <% beer_clubs.each do |beer_club| %>
      <tr>
        <td><%= link_to beer_club.name, beer_club %></td>
        <td><%= beer_club.founded %></td>
        <td><%= beer_club.city %></td>
      </tr>
  <% end %>
  </tbody>

  <tfoot>
  <tr>
    <th>Name</th>
    <th>Founded</th>
    <th>City</th>
  </tr>
  </tfoot>
</table>

app/views/beer_clubs/edit.html.erb
<h1>Editing beer club</h1>

<%= render 'form' %>

<span class="tools">
<%= link_to 'Show', @beer_club %>
<%= link_to 'Back', beer_clubs_path %>
</span>

app/views/beer_clubs/index.html.erb
<h1>Listing beer clubs</h1>

<% if not @beer_clubs.empty? %>
    <%= render 'list', beer_clubs:@beer_clubs %>
<% else %>
    <p>No known beer clubs.</p>
<% end %>

<%= link_to 'New Beer club', new_beer_club_path if current_user %>

app/views/beer_clubs/new.html.erb
<h1>New beer club</h1>

<%= render 'form' %>

<span class="tools">
<%= link_to 'Back', beer_clubs_path %>
</span>

app/views/beer_clubs/show.html.erb
<h1>
  <%= @beer_club.name %>
</h1>

<p id="notice"><%= notice %></p>

<p>
  <strong>Founded:</strong>
  <%= @beer_club.founded %>
</p>

<p>
  <strong>City:</strong>
  <%= @beer_club.city %>
</p>

<h2>Members</h2>
<ul>
  <% @beer_club.memberships.confirmed.each do |membership| %>
      <li>
        <%= link_to membership.user.username, membership.user %>
      </li>
  <% end %>
</ul>


<% if @beer_club.member?(current_user) %>
  <h2>Applications</h2>
  <% if @beer_club.memberships.unconfirmed.empty? %>
    <p>No unconfirmed applications.</p>
  <% else %>
    <ul>
      <% @beer_club.memberships.unconfirmed.each do |application| %>
        <li>
          <%= link_to 'Accept', confirm_membership_path(application.id), method: :post, class: 'tool' %>
          <%= link_to application.user.username, application.user %>
        </li>
      <% end %>
    </ul>
  <% end %>
<% end %>

<% if current_user %>
    <% unless @beer_club.memberships.find_by user_id:current_user.id %>
      <div>
        <%= form_for(@membership) do |f| %>
          <%= f.hidden_field(:beer_club_id)%>
          <%= f.submit 'Join the club' %>
        <% end %>
      </div>
    <%end %>
<% end %>

<span class="tools">
  <% if current_user %>
    <%= link_to 'Edit', edit_beer_club_path(@beer_club) %>
    <%= link_to 'Destroy', @beer_club, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
  <%= link_to 'Back', beer_clubs_path %>
</span>