config/routes.rb
Ratebeer::Application.routes.draw do
  resources :memberships, only: [:new, :create, :destroy] do
    post 'confirm', on: :member
  end

  resources :beer_clubs

  resources :users

  resources :beers
  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  root 'breweries#index'
  get 'brewerylist', to:'breweries#nglist'

  resources :styles

  resources :sessions, only: [:new, :create, :destroy]

  resources :ratings, only: [:index, :new, :create, :destroy]

  resources :places, only: [:index, :show]
  post 'places', to: 'places#search'

  get 'kaikki_bisset', to: 'beers#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#omniauth'
  get 'auth:/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy'

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  include RatingAverage

  validates_presence_of :name
  validates_presence_of :year
  validates_numericality_of :year, {greater_than_or_equal_to: 1042,
                                    only_integer: true}
  validate :year_not_in_future

  scope :active,  -> { where active:true }
  scope :retired, -> { where active:[nil, false] }

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  def year_not_in_future
    unless year.nil?
      if Date.today.year < year
        errors.add(:year, "can't be in the future")
      end
    end
  end

  def print_report
    puts name
    puts "established at year #{year}"
    puts "number of beers #{beers.count}"
    puts "number of ratings #{ratings.count}"
  end

  def restart
    self.year = 2014
    puts "Changer year to #{year}"
  end

  def self.top(number)
    all.includes(:ratings).sort_by{ |b| -(b.average_rating or 0) }.take number
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :nglist]
  before_action :ensure_that_admin, only: [:destroy]
  before_action :skip_if_cached, only: [:index]

  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all.includes(:ratings, :beers)
    @active_breweries = Brewery.includes(:ratings, :beers).active
    @retired_breweries = Brewery.includes(:ratings, :beers).retired

    case @order
      when 'name' then
        @breweries.sort_by!{ |b| b.name }
        @active_breweries.sort_by!{ |b| b.name }
        @retired_breweries.sort_by!{ |b| b.name }

      when 'year' then
        @active_breweries.sort_by!{ |b| b.year }
        @retired_breweries.sort_by!{ |b| b.year }
        @breweries.sort_by!{ |b| b.year }
    end
  end

  # GET /ngbrewerylist
  def nglist
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        ["brewerylist-name", "brewerylist-year"].each{ |f| expire_fragment(f) }
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render action: 'show', status: :created, location: @brewery }
      else
        format.html { render action: 'new' }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        ["brewerylist-name", "brewerylist-year"].each{ |f| expire_fragment(f) }
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
    ["brewerylist-name", "brewerylist-year"].each{ |f| expire_fragment(f) }
    respond_to do |format|
      format.html { redirect_to breweries_url }
      format.json { head :no_content }
    end
  end

  # POST /breweries/1/toggle_activity
  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)

    new_status = brewery.active? ? "active" : "retired"
    ["brewerylist-name", "brewerylist-year"].each{ |f| expire_fragment(f) }

    redirect_to :back, notice:"Brewery activity status changed to #{new_status}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :year, :active)
    end

    # Check cache in case of html request, if json just run with it
    def skip_if_cached
      @order = params[:order] || 'name'
      respond_to do |format|
        format.html{ return render :index if fragment_exist? "brewerylist-#{@order}" }
        format.json{}
      end
    end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :active %> <br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<table>
  <thead>
    <tr>
      <% if current_page?(breweries_path) or current_page?(root_path) %>
        <th> <%= link_to 'Name', breweries_path(order:'name') %> </th>
        <th> <%= link_to 'Year', breweries_path(order:'year') %> </th>
      <% else %>
        <th>Name</th>
        <th>Year</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
      </tr>
    <% end %>
  </tbody>

  <tfoot>
    <tr>
      <% if current_page?(breweries_path) %>
        <th> <%= link_to 'Name', breweries_path(order:'name') %> </th>
        <th> <%= link_to 'Year', breweries_path(order:'year') %> </th>
      <% else %>
        <th>Name</th>
        <th>Year</th>
      <% end %>
    </tr>
  </tfoot>
</table>

app/views/breweries/edit.html.erb
<h1>Editing brewery</h1>

<%= render 'form' %>

<span class="tools">
<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>
</span>

app/views/breweries/index.html.erb
<h1>Listing breweries</h1>

<% cache "brewerylist-#{@order}", skip_digest:true do %>

<h2>Active</h2>
<% if not @active_breweries.empty? %>
    <%= render 'list', breweries:@active_breweries %>
<% else %>
    No known active breweries.
<% end %>

<h2>Retired</h2>
<% if not @retired_breweries.empty? %>
    <%= render 'list', breweries:@retired_breweries %>
<% else %>
    No known retired breweries.
<% end %>

<% end %>

<%= link_to 'New Brewery', new_brewery_path if current_user %><br/>

app/views/breweries/new.html.erb
<h1>New brewery</h1>

<%= render 'form' %>

<span class="tools">
<%= link_to 'Back', breweries_path %>
</span>

app/views/breweries/nglist.html.erb
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.10/angular.min.js"></script>
<script>
    function BreweriesController($scope, $http) {
        $http.get('breweries.json').success( function(data, status, headers, config) {
            $scope.breweries = data;
        });

        $scope.order = 'name';

        $scope.click = function (order){
            $scope.order = order;
            console.log(order);
        }

        $scope.searchText = '';
    }
</script>

<h1>Breweries</h1>

<div ng-app ng-controller="BreweriesController">
  <form>
    <label for="search">Search</label> <br/>
    <input type="text" name="search" ng-model="searchText" />
  </form>

  <table>
    <thead>
    <th> <a ng-click="click('name')">Name</a> </th>
    <th> <a ng-click="click('year')">Year</a> </th>
    <th> <a ng-click="click('beers.count')">Beers</a> </th>
    </thead>
    <tbody>
      <tr ng-repeat="brewery in breweries| orderBy:order | filter:searchText">
        <td>{{brewery.name}}</td>
        <td>{{brewery.year}}</td>
        <td>{{brewery.beers.count}}</td>
      </tr>
    </tbody>
    <tfoot>
      <th> <a ng-click="click('name')">Name</a> </th>
      <th> <a ng-click="click('year')">Year</a> </th>
      <th> <a ng-click="click('beers')">Beers</a> </th>
    </tfoot>
  </table>

</div>

app/views/breweries/show.html.erb
<% cache @brewery do %>

<h1>
  <%= @brewery.name %> <br />
  <% if not @brewery.active  %>
      <span class="retired">Retired</span>
  <% end %>
</h1>

<p id="notice"><%= notice %></p>

<p>
  <i>Established <%= @brewery.year %></i><br />
  <% if not @brewery.active  %>
      <span class="retired">Retired</span>
  <% end %>
</p>

<h2>Beers</h2>
<% if @brewery.beers.empty? %>
    No known beers.
<% else %>
    <%= render 'beers/list', beers:@brewery.beers %>
<% end %>

<h2>Ratings</h2>
<p>
  <% if @brewery.ratings.empty? %>
      The brewery has no ratings!
  <% else %>
      Has <%=pluralize(@brewery.ratings.count, 'rating')%>, average rating <%= round(@brewery.average_rating) %>
  <% end %>
</p>

<% end #cache%>

<span class="tools">
  <%= link_to 'change activity', toggle_activity_brewery_path(@brewery.id), method: :post %>
</span>

<span class="tools">
  <% if current_user %>
    <%= link_to 'Edit', edit_brewery_path(@brewery) %>
    <%= link_to 'Destroy', @beer_club, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
  <%= link_to 'Back', breweries_path %>
</span>