config/routes.rb
Ratebeer::Application.routes.draw do
  resources :memberships, only: [:new, :create, :destroy] do
    post 'confirm', on: :member
  end

  resources :beer_clubs

  resources :users

  resources :beers
  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  root 'breweries#index'
  get 'brewerylist', to:'breweries#nglist'

  resources :styles

  resources :sessions, only: [:new, :create, :destroy]

  resources :ratings, only: [:index, :new, :create, :destroy]

  resources :places, only: [:index, :show]
  post 'places', to: 'places#search'

  get 'kaikki_bisset', to: 'beers#index'

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  get 'auth/:provider/callback', to: 'sessions#omniauth'
  get 'auth:/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ratebeer</title>
  <link href='http://fonts.googleapis.com/css?family=Quicksand' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navibar">
  <span class="browse_content_nav">
    <%= link_to 'Breweries', breweries_path %>
    <%= link_to 'Beers', beers_path %>
    <%= link_to 'Clubs', beer_clubs_path %>
    <%= link_to 'Places', places_path %>
    <%= link_to 'Ratings', ratings_path %>
    <%= link_to 'Styles', styles_path %>
  </span>

  <% if not current_user.nil? %>
    <span class="add_content_nav">
      <%= link_to 'Rate a beer', new_rating_path %>
      <%= link_to 'Join a club', new_membership_path %>
    </span>
    <span class="user_management_nav">
      <%= link_to current_user.username, current_user %>
      <%= link_to 'Signout', signout_path, method: :delete %>
    </span>
  <% else %>
    <span class="user_management_nav">
      <%= link_to 'Signup', new_user_path %>
      <%= link_to 'Signin', new_session_path %>
    </span>
  <% end %>

</div>

<div class="content">
  <%= yield %>
</div>

</body>
</html>